### ISSUE TITLE
Pretendard JP 가변 다이나믹 서브셋 사용 시 `font-family`를 'Pretendard JP'로 설정해야 정상 작동합니다.

### ISSUE THREAD

**Issue by segln** [orioncactus/pretendard#188]
Pretendard JP 가변 다이나믹 서브셋 사용 중입니다. 다른 서브셋의 경우는 테스트해 보지 않았습니다.

font-family를 'Pretendard JP Variable'로 적용하면 알파벳에는 정상적으로 적용되지만, 한글에는 그렇지 않습니다.
font-family를 'Pretendard JP'로 설정하면 정상 작동합니다. 

### 환경

Windows 11 Pro 23H2
Chrome 122.0
Firefox 123.0

Windows Sandbox 이용 격리된 환경에서 실험했으며, 매 시도는 캐시 삭제 후 진행되었습니다.

#### 이용한 CSS

```css
@import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-jp-dynamic-subset.min.css");
```

### README에서 권장하는 사용법 (한글이 작동하지 않으며, 기본 fallback 폰트로 표시됨)
```
html {
    font-family: 'Pretendard JP Variable';
}
```

### 실제 작동하는 사용법
```
html {
    font-family: 'Pretendard JP';
}
```

**Comment by segln** [comment]
### 테스트 소스

#### 1.html
```html
<!DOCTYPE HTML>
<head>
    <link rel="stylesheet" type="text/css" href="./font.css">
</head>
<body>
	<div id="test-nonvariable">No Variable; 테스트:프리텐다드</div>
	<div id="test-withvariable">With Variable; 테스트:프리텐다드</div>

	<div id="test-nonvariable" style="font-weight: 900">No Variable; 900; 테스트:프리텐다드</div>
	<div id="test-withvariable" style="font-weight: 900">With Variable; 900; 테스트:프리텐다드</div>
</body>
```

#### font.css
```css
@import url("https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-jp-dynamic-subset.min.css");

#test-nonvariable {
    font-family: 'Pretendard JP'
}

#test-withvariable {
    font-family: 'Pretendard JP Variable'
}
```

### 스크린샷

![image](https://github.com/orioncactus/pretendard/assets/18192378/aaf54a03-074d-4819-bb9a-929e14471dd6)
